apiVersion: 1

datasources:
  # Loki datasource using our ClickHouse adapter
  - name: Loki (ClickHouse)
    type: loki
    access: proxy
    url: http://lgtm-adapter:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          matcherRegex: "trace_id=(\\w+)"
          url: "http://localhost:3001/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Tempo%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D"
          datasourceUid: "tempo"
    uid: loki-clickhouse

  # Direct ClickHouse datasource for advanced queries
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: default
    username: default
    password: ""
    editable: true
    jsonData:
      defaultDatabase: default
      defaultTable: otel_logs
      port: 8123
      server: clickhouse
      username: default
      tlsSkipVerify: false
      useYandexCloudAuthorization: false
      xHeaderKey: ""
      xHeaderUser: ""
    uid: clickhouse

  # TestData datasource for examples
  - name: TestData
    type: testdata
    access: proxy
    uid: testdata